### ISSUE TITLE
rcttrss service won't start (daemon illegal option --t)

### ISSUE THREAD

**Issue by edwardjohnson11** [Zerotronic/rc-ttrss#2]
I seem to be having an issue that seems to have arisen after I pkg update && pkg upgrade my php packages. The rcttrss service won't start now because of the following lines:

```
root@tt-rss:/ # sh -x /usr/local/etc/rc.d/rcttrss start
[...]
+ echo 'Starting rcttrss update daemon.'
Starting rcttrss update daemon.
+ exec /usr/sbin/daemon -c -t rcttrss -P /var/run/rcttrss.pid -u ttrss /usr/bin/php /usr/local/www/apache24/data/tt-rss/update_daemon2.php
daemon: illegal option -- t
usage: daemon [-cfr] [-p child_pidfile] [-P supervisor_pidfile] [-u user]
              command arguments ...
root@tt-rss:/ #
```

**Comment by Zerotronic** [comment]
What version is your FreeBSD box?
The problem does not seem to be with the rcttrss service, but with the daemon(8) package in your system. According to what you posted above, daemon(8) considers **_-t_** an illegal option for some reason. If you take a look in the [manpages](https://www.freebsd.org/cgi/man.cgi?query=daemon&sektion=8) you can see that the **_-t_** option is there so that the daemon process can have a title, i.e. if you run **ps** for example you can identify the process by it's name like so:
`root@tt-rss:~ # ps -aux | grep -v grep | grep rcttrss`
`[...]`
`root       37275   0.0  0.1   10468   2156  -  Ss   14:11      0:00.01 daemon: rcttrss[37276] (daemon)`
`[...]`
If you remove the **_-t_** option from the invocation you would get something like this:
`root@tt-rss:~ # ps -aux | grep -v grep | grep daemon`
`[...]`
`root       37219   0.0  0.1   10468   2156  -  Ss   14:09      0:00.00 daemon: /usr/local/www/apache24/data/tt-rss/update_daemon2.php[37220] (daemon)`
`[...]`
So as you can see that is not that big a deal. As a workaround you could edit the rcttrss file and remove 

> **_-t ${name}_**

 from line **169**. 
However if i were you i would take a look at my system and figure out why daemon(8) is not working properly. In your system, according to your post, daemon(8) appears to have the following usage:
`usage: daemon [-cfr] [-p child_pidfile] [-P supervisor_pidfile] [-u user]`
`              command arguments ...`
Same thing from my system (fully updated FreeBSD 11.1):
`usage: daemon [-cfrS] [-p child_pidfile] [-P supervisor_pidfile]`
`              [-u user] [-o output_file] [-t title]`
`              [-l syslog_facility] [-s syslog_priority]`
`              [-T syslog_tag] [-m output_mask]`
`command arguments ...`

Hope this helps you

**Comment by edwardjohnson11** [comment]
Thank you for such a detailed write-up! I will test in the coming week and revert.

My box is a Freenas 9.10 jail (FreeBSD 10.3), which is what I was running when I first installed rcttrss. For some reason it just stopped working out of the blue...

In the meantime, given that my Freenas box is not completely headless, I am running php ./update_daemon2.php manually in a tty.
